from dataclasses import dataclass
from datetime import datetime
from typing import Any


@dataclass
class Alert:
    """
    Represents a runtime security alert generated by a detector.
    """

    sid: int
    title: str
    severity: str

    source: str
    timestamp: datetime

    log: Any