from dataclasses import dataclass
from datetime import datetime
from typing import Any


@dataclass
class Alert:
    """
    Represents a runtime security alert generated by a detector.
    """

    sid: int | None

    title: str
    description: str

    severity: str
    source: str

    detection_method: str

    timestamp: datetime

    log: Any

    first_seen: datetime | None = None
    last_seen: datetime | None = None

    occurrences: int = 1

    status: str = "active"

    ml_model: str | None = None
    ml_confidence: float | None = None

    def __post_init__(self):

        if self.first_seen is None:
            self.first_seen = self.timestamp

        if self.last_seen is None:
            self.last_seen = self.timestamp