from dataclasses import dataclass
from datetime import datetime
from typing import Any


@dataclass
class Alert:
    """
    Represents a runtime security alert generated by a detector.
    """

    sid: int | None

    title: str
    description: str

    severity: str
    source: str

    detection_method: str

    timestamp: datetime

    log: Any

    ml_model: str | None = None
    ml_confidence: float | None = None